import AuthProvider from '@/components/auth/AuthProvider'
import '@/styles/globals.css'
import { Inter as FontSans } from 'next/font/google'
import localFont from 'next/font/local'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`min-h-screen dark bg-background font-sans antialiased ${fontSans.variable} ${fontHeading.variable}`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
